version: 2
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - go-111
      - deploy:
          requires:
            - go-111
          filters:
            branches:
              only:
                - master
                - feature/circleci
jobs:
  deploy:
    docker:
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/wellington/wellington
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          make release
      - store_artifacts:
          path: snapshot/
      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          make push
  "go-111":
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: circleci/golang:1.11
    working_directory: /go/src/github.com/wellington/wellington
    #environment:
    #  TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache
      - run: make test
      - save_cache:
          key: v1-pkg-cache
          paths:
            - "/go/pkg"
